In [9]:
import pandas as pd
path = "/home/pasoneto/Documents/Ciência/PhD/data/treatment/"

base = pd.read_csv(path+"sem_duplica_real.csv")

previsores = base.iloc[:, 2:5].values
classe = base.iloc[:, 6].values

In [95]:
#Arvore de decisao

In [10]:
from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.15, random_state=0)

from sklearn.tree import DecisionTreeClassifier
classificador = DecisionTreeClassifier(criterion='entropy', random_state=0)
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

from sklearn.model_selection import cross_val_score
resultados = cross_val_score(classificador, previsores, classe, cv = 10)
resultados.mean()

0.3302800283805475

In [11]:
resultados.std()

0.009294371169855804

In [ ]:
#Naive Bayes

In [12]:
from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.15, random_state=0)
 
from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)
 
from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

from sklearn.model_selection import cross_val_score
resultados = cross_val_score(classificador, previsores, classe, cv = 10)
resultados.mean()

0.3329973227094511

In [13]:
resultados

array([0.33216477, 0.34078457, 0.32478632, 0.33793557, 0.33333333,
       0.32544379, 0.32610125, 0.33903134, 0.3396888 , 0.33070348])

In [ ]:
#Regressao Logistica

In [14]:
from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.15, random_state=0)

from sklearn.linear_model import LogisticRegression
classificador = LogisticRegression(solver='lbfgs')
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

from sklearn.model_selection import cross_val_score
resultados = cross_val_score(classificador, previsores, classe, cv = 10)
resultados.mean()

0.33319459017901687

In [90]:
resultados

array([0.33459388, 0.34215719, 0.34824071, 0.34511674, 0.35120026,
       0.34780464, 0.3473113 , 0.34303568, 0.34632462, 0.33760895])

In [ ]:
#Random Forest

In [15]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
labelencoder_classe = LabelEncoder()

classe = labelencoder_classe.fit_transform(classe)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.15, random_state=0)

from sklearn.ensemble import RandomForestClassifier
classificador = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

from sklearn.model_selection import cross_val_score
resultados = cross_val_score(classificador, previsores, classe, cv = 10)
resultados.mean()

0.3305647750079086

In [81]:
resultados

array([0.75402828, 0.7474515 , 0.6132851 , 0.53567905, 0.53485695,
       0.55467851, 0.5306693 , 0.52162473, 0.53297155, 0.52590035])

In [ ]:
#SVM

In [ ]:
labelencoder_classe = LabelEncoder()
classe = labelencoder_classe.fit_transform(classe)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.15, random_state=0)

from sklearn.svm import SVC
classificador = SVC(kernel = 'sigmoid', random_state = 1)
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

from sklearn.model_selection import cross_val_score
resultados = cross_val_score(classificador, previsores, classe, cv = 10)
resultados.mean()

In [83]:
resultados

array([0.34297928, 0.34363696, 0.35169352, 0.34774745, 0.34758303,
       0.34369347, 0.33777339, 0.34879132, 0.34402236, 0.3494491 ])

In [16]:
labelencoder_classe = LabelEncoder()
classe = labelencoder_classe.fit_transform(classe)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.15, random_state=0)

from sklearn.neural_network import MLPClassifier
classificador = MLPClassifier(verbose = True, max_iter=1000, tol=0.00010)
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)
print(classificador.out_activation_)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

Iteration 1, loss = 1.10108166
Iteration 2, loss = 1.09956422
Iteration 3, loss = 1.09921216
Iteration 4, loss = 1.09890697
Iteration 5, loss = 1.09893873
Iteration 6, loss = 1.09856876
Iteration 7, loss = 1.09869467
Iteration 8, loss = 1.09859039
Iteration 9, loss = 1.09860421
Iteration 10, loss = 1.09844872
Iteration 11, loss = 1.09834849
Iteration 12, loss = 1.09832282
Iteration 13, loss = 1.09835032
Iteration 14, loss = 1.09823892
Iteration 15, loss = 1.09821778
Iteration 16, loss = 1.09823428
Iteration 17, loss = 1.09835342
Iteration 18, loss = 1.09808678
Iteration 19, loss = 1.09809057
Iteration 20, loss = 1.09823384
Iteration 21, loss = 1.09802747
Iteration 22, loss = 1.09804039
Iteration 23, loss = 1.09798940
Iteration 24, loss = 1.09810521
Iteration 25, loss = 1.09790566
Iteration 26, loss = 1.09792818
Iteration 27, loss = 1.09791866
Iteration 28, loss = 1.09785059
Iteration 29, loss = 1.09792515
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. S

In [17]:
precisao

0.33425858290723154